version: '2'
services:
  zookeeper:
    container_name: zookeeper_container
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - red-global
  kafka:
    container_name: kafka_container
    image: wurstmeister/kafka
    ports:
      - "9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "flight_delay_classification_request:1:1"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092
    networks:
      - red-global

  mongo:
    container_name: mongo_container
    image: mongo:3.4
    command: --nojournal --noauth
    #./resources/import_distances.sh
    networks:
      - red-global
    volumes:
      - ../data:/data/db
      - ../resources:/resources
    ports:
      - "27017:27017"
  
networks: 
  red-global: