version: '2'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper_container
    ports:
      - "2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka_container
    ports:
      - "9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "flight_delay_classification_request:1:1"

  mongo:
    image: alvarake/mongo_fbid:3.0
    container_name: mongo_container
    command: --nojournal --noauth
    ports:
      - "27017"

  spark-master:
    image: bde2020/spark-master:2.4.4-hadoop2.7
    container_name: spark-master
    ports:
      - "8080"
      - "7077"
      - "9001"
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - JAVA_HOME=/usr
      - SPARK_HOME=/spark
      - "constraint:node==spark-master"
    volumes:
      - ../prediction:/prediction-job
      - ../models:/models

  spark-submiter:
    image: alvarake/spark-worker_fbid:4.3
    container_name: spark-submiter
    depends_on:
      - spark-master
    ports:
      - "8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "constraint:node==spark-submiter"
  
  spark-worker-1:
    image: bde2020/spark-worker:2.4.4-hadoop2.7
    container_name: spark-worker1
    depends_on:
      - spark-master
    ports:
      - "8082"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "constraint:node==spark-worker-1"
    volumes:
      - ../prediction:/prediction-job
      - ../models:/models

  spark-worker-2:
    image: bde2020/spark-worker:2.4.4-hadoop2.7
    container_name: spark-worker2
    depends_on:
      - spark-master
    ports:
      - "8083"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "constraint:node==spark-worker-2"
    volumes:
      - ../prediction:/prediction-job
      - ../models:/models
    

  web:
    image: alvarake/web_fbid:latest
    container_name: web
    ports:
      - "80:80"
