version: '2'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper_container
    ports:
      - "2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka_container
    ports:
      - "9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "flight_delay_classification_request:1:1"

  mongo:
    image: alvarake/mongo_fbid
    container_name: mongo_container
    command: --nojournal --noauth
    volumes:
      - ../data:/data/db
    ports:
      - "27017"

  spark-master:
    image: bde2020/spark-master:2.4.4-hadoop2.7
    container_name: spark-master
    ports:
      - "8080"
      - "7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - JAVA_HOME=/usr
      - SPARK_HOME=/spark

  spark-worker-1:
    image: alvarake/spark-worker_fbid
    container_name: spark-worker
    depends_on:
      - spark-master
    ports:
      - "8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"

  web:
    image: alvarake/web_fbid
    container_name: web
    ports:
      - "5000:5000"
