apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o 2kompose
    kompose.version: 1.19.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: spark-worker-2
  name: spark-worker-2
spec:
  ports:
  - name: "8083"
    port: 8083
    targetPort: 8083
  selector:
    io.kompose.service: spark-worker-2
status:
  loadBalancer: {}
