apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o 2kompose
    kompose.version: 1.19.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: spark-submiter
  name: spark-submiter
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o 2kompose
        kompose.version: 1.19.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: spark-submiter
    spec:
      containers:
      - args:
        - sh
        - -c
        - sleep 12 && /prediction-job/startpredicition.sh
        env:
        - name: SPARK_MASTER
          value: spark://spark-master:7077
        - name: constraint
          value: node==spark-submiter
        image: alvarake/spark-worker_fbid:7.0
        name: spark-submiter
        ports:
        - containerPort: 8081
        resources: {}
      restartPolicy: Always
status: {}
