apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o 2kompose
    kompose.version: 1.19.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: spark-submiter
  name: spark-submiter
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    io.kompose.service: spark-submiter
status:
  loadBalancer: {}
