apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: spark-worker-1
  name: spark-worker-1
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: spark-worker-1
    spec:
      containers:
      - env:
        - name: SPARK_MASTER
          value: spark://spark-master:7077
        image: alvarake/spark-worker_fbid
        name: spark-worker
        ports:
        - containerPort: 8081
        resources: {}
      restartPolicy: Always
status: {}
