apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-11-28T15:16:21Z"
  generateName: web-
  labels:
    io.kompose.service: web
  name: web-service
  namespace: default
  resourceVersion: "11337"
  selfLink: /api/v1/namespaces/default/services/web-zm9sc
  uid: 08e31a71-11f2-11ea-8425-42010af001c4
spec:
  clusterIP: 10.7.253.176
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30888
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    io.kompose.service: web
  sessionAffinity: None
  type: LoadBalancer
