apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.19.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: spark-master
  name: spark-master
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.19.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: spark-master
    spec:
      containers:
      - env:
        - name: INIT_DAEMON_STEP
          value: setup_spark
        - name: JAVA_HOME
          value: /usr
        - name: SPARK_HOME
          value: /spark
        image: bde2020/spark-master:2.4.4-hadoop2.7
        name: spark-master
        ports:
        - containerPort: 8080
        - containerPort: 7077
        resources: {}
        volumeMounts:
        - mountPath: /prediction-job
          name: spark-master-claim0
        - mountPath: /models
          name: spark-master-claim1
      restartPolicy: Always
      volumes:
      - name: spark-master-claim0
        persistentVolumeClaim:
          claimName: spark-master-claim0
      - name: spark-master-claim1
        persistentVolumeClaim:
          claimName: spark-master-claim1
status: {}
