apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.19.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: spark-worker-1
  name: spark-worker-1
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.19.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: spark-worker-1
    spec:
      containers:
      - args:
        - bash
        - -c
        - sleep 12 && /spark/bin/spark-submit --packages org.apache.spark:spark-sql-kafka-0-10_2.11:2.4.4,org.mongodb.spark:mongo-spark-connector_2.11:2.4.1
          --class es.upm.dit.ging.predictor.MakePrediction --master local /prediction-job/flight_prediction_2.11-0.1.jar
        env:
        - name: SPARK_MASTER
          value: spark://spark-master:7077
        image: bde2020/spark-worker:2.4.4-hadoop2.7
        name: spark-worker-1
        ports:
        - containerPort: 8081
        resources: {}
        volumeMounts:
        - mountPath: /prediction-job
          name: spark-worker-1-claim0
        - mountPath: /models
          name: spark-worker-1-claim1
      restartPolicy: Always
      volumes:
      - name: spark-worker-1-claim0
        persistentVolumeClaim:
          claimName: spark-worker-1-claim0
      - name: spark-worker-1-claim1
        persistentVolumeClaim:
          claimName: spark-worker-1-claim1
status: {}
